### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Sekretz** [MartinCazares/UnrealEngine-Brownie#1]
Thank you for making such a wonderful stuff.

Can you please add In-App Update system like this https://developer.android.com/guide/playcore/in-app-updates

 and Native sharing 

like copying strings/text/integer value to other apps like this https://developer.android.com/training/sharing/send

**Comment by MartinCazares** [comment]
I think both cases are good additions to the library.

- Adding In-App (Immediate Updates)
- Adding text/* (Sharing)

Release v1.1.0

**Comment by MartinCazares** [comment]
Both features have been added in v1.1.0 which should be live, soon...

**Comment by 1unknwn** [comment]
Just curious, When will it go live ?

**Comment by Sekretz** [comment]
> Both features have been added in v1.1.0 which should be live, soon...

It isn't live yet

**Comment by MartinCazares** [comment]
Unreal Marketplace is very slow in reviewing the new releases, it is still in the process of review even tho the changes are just a few...

**Comment by Sekretz** [comment]
> Unreal Marketplace is very slow in reviewing the new releases, it is still in the process of review even tho the changes are just a few...

So it is now a paid one !
